name: 自动编译 WinUI 3 应用

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 .NET 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: 恢复项目依赖
      # 加入强制 x64 参数，防止恢复依赖时出错
      run: dotnet restore -p:Platform=x64

    - name: 执行编译与发布
      # 移除了 -o 参数，并加入了 -p:Platform=x64 和 -p:PlatformTarget=x64 强制镇压 ARM64 冲突
      run: dotnet publish -c Release -r win-x64 -p:Platform=x64 -p:PlatformTarget=x64 --self-contained true

    - name: 上传编译结果供下载
      uses: actions/upload-artifact@v4
      with:
        name: 编译完成的软件包
        # 既然不能指定输出目录，我们就用通配符，让它自动去默认的 Release 目录下把 publish 文件夹抓出来打包
        path: '**/bin/Release/**/publish'
